### ISSUE TITLE
Configurate-YAML erroring while loading floats

### ISSUE THREAD

**Issue by egg82** [SpongePowered/Configurate#198]
Discovered on-stream today as I was doing a plugin challenge.

Saving a float to a YAML file and then loading that float back in seems to make Configurate less-than-happy.
For example, saving pitch/yaw for a location to a YAML file and loading it back. Even for relatively small and normal numbers.

Current workaround is to use doubles instead.

```
[10:53:14] [Server thread/ERROR]: [me.egg82.wp.Warps] me.egg82.dc.external.org.spongepowered.configurate.serialize.SerializationException: [warps, test_warp, pitch]: Value -34.050217 is out of bounds of a float
me.egg82.dc.external.org.spongepowered.configurate.serialize.SerializationException: [warps, test_warp, pitch]: Value -34.050217 is out of bounds of a float
	at me.egg82.dc.external.org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$1(NumericSerializers.java:91) ~[?:?]
	at me.egg82.dc.external.org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[?:?]
	at me.egg82.dc.external.org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[?:?]
	at me.egg82.dc.external.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[?:?]
	at me.egg82.dc.external.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[?:?]
	at me.egg82.dc.external.org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[?:?]
	at me.egg82.dc.external.org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[?:?]
	at me.egg82.dc.external.org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:433) ~[?:?]
	at me.egg82.wp.utils.WarpFileUtil.loadData(WarpFileUtil.java:65) ~[?:?]
	at me.egg82.wp.Warps.onEnable(Warps.java:77) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-585]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-585]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-585]
	at java.lang.Thread.run(Thread.java:829) [?:?]
	Suppressed: me.egg82.dc.external.org.spongepowered.configurate.serialize.SerializationException: [warps, test_warp, yaw]: Value -46.652115 is out of bounds of a float
		at me.egg82.dc.external.org.spongepowered.configurate.serialize.NumericSerializers.lambda$static$1(NumericSerializers.java:91) ~[?:?]
		at me.egg82.dc.external.org.spongepowered.configurate.serialize.FunctionScalarSerializer.deserialize(FunctionScalarSerializer.java:40) ~[?:?]
		at me.egg82.dc.external.org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:115) ~[?:?]
		at me.egg82.dc.external.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:64) ~[?:?]
		at me.egg82.dc.external.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:48) ~[?:?]
		at me.egg82.dc.external.org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:204) ~[?:?]
		at me.egg82.dc.external.org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[?:?]
		at me.egg82.dc.external.org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:433) ~[?:?]
		at me.egg82.wp.utils.WarpFileUtil.loadData(WarpFileUtil.java:65) ~[?:?]
		at me.egg82.wp.Warps.onEnable(Warps.java:77) ~[?:?]
		at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-585]
		at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-585]
		at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-585]
		at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-585]
		at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-585]
		at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-585]
		at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-585]
		at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-585]
		at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-585]
		at java.lang.Thread.run(Thread.java:829) [?:?]
```

**Comment by zml2008** [comment]
This is a fun one, thanks for reporting! There's a few things that cause this issue -- first off, the precision-loss calculation I used in 4.0.0 was wrong. That can be fixed, but brings up another issue: your coordinate cannot be represented precisely as a 32-bit floating-point value. While it looks like a short decimal number, remember that floating-point numbers are stored as binary values. If you look at a [floating-point calculator](https://float.exposed/0xc041066d82ba5a04), you can see that even using up quite a lot of the available bits in a `double` won't represent the value `-34.050217` exactly.

The YAML format (as with others such as JSON and HOCON) has no way to distinguish between 32-bit and 64-bit floats, so Configurate has to guess what the intent of the user is. After going down this rabbit hole, I think the only way to balance those competing interests is to make the precision-loss checks a lot more lenient -- the upcoming fix will only verify that the exponent of a 64-bit float input is within the range of a 32-bit float, and not check the significand at all. Any further validation would be up to the end-user.

(as an aside, if you want an interesting read, take a look at [the code behind Float.parseFloat](https://github.com/openjdk/jdk/blob/8fa50ebdf2c0e44316d8e4b64b3e8ef90a2cc1bb/src/java.base/share/classes/jdk/internal/math/FloatingDecimal.java#L1034) -- it's a good peek into the complexity behind such a core component of the language that we rarely think about)
