### ISSUE TITLE
4.1.1 Unsupported class file major version 60 via class loading

### ISSUE THREAD

**Issue by AlessioDP** [SpongePowered/Configurate#207]
Hello, I have an issue similar to #204 
I open a different issue because its not related to project compiling but due to jar class loading in runtime.

This is the stackpath:
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.alessiodp.parties.core.common.addons.external.libby.relocation.RelocationHelper.relocate(RelocationHelper.java:123) ~[?:?]
        at com.alessiodp.parties.core.common.addons.external.libby.LibraryManager.relocate(LibraryManager.java:386) ~[?:?]
        at com.alessiodp.parties.core.common.addons.external.libby.LibraryManager.loadLibrary(LibraryManager.java:415) ~[?:?]
        at com.alessiodp.parties.core.common.addons.ADPLibraryManager.setupLibrariesForYAML(ADPLibraryManager.java:45) ~[?:?]
        at com.alessiodp.parties.core.common.storage.StorageType.initLibraries(StorageType.java:39) ~[?:?]
```
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:195) ~[?:?]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176) ~[?:?]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162) ~[?:?]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283) ~[?:?]
        at me.lucko.jarrelocator.JarRelocatorTask.processClass(JarRelocatorTask.java:114) ~[?:?]
```

The plugin (Parties) uses the library `libby` to externally load `configurate` and `configurate-yaml` (the first one have this issue, the second one loads correctly).
`jar-relocator` + `asm` have been used to load and relocate the library `configurate`.

This has been tested with Java 11 OpenJDK + Paper 1.16.5 MC server.

**Comment by zml2008** [comment]
You are using an outdated ASM version. Either update it, or exclude the multi-release variant from transformation. Not a configurate issue.
