### ISSUE TITLE
Allow (de)serialization of Maps

### ISSUE THREAD

**Issue by Peter-Crawley** [SpongePowered/Configurate#318]
Current work arround is to have a wrapper which works fine, but results in a slightly less clean configuration file.

**Comment by zml2008** [comment]
you should be anle to deserialize maps just fine, what is your issue?

**Comment by Peter-Crawley** [comment]
```
org.spongepowered.configurate.serialize.SerializationException: [] of type java.util.Map: Raw types are not supported
	at org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:127) ~[configurate-core-4.1.2.jar:?]
	at org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:520) ~[configurate-core-4.1.2.jar:?]
	at net.horizonsend.ion.server.managers.PlanetsManager.<init>(PlanetsManager.kt:28) ~[Ion.jar:?]
	at net.horizonsend.ion.server.IonServer.onEnable(IonServer.kt:135) ~[Ion.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-135]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-135]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-135]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-135]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-135]
```

**Comment by zml2008** [comment]
the issue you are having there is that you need to provide type parameters - look at the TypeToken overload.
