### ISSUE TITLE
Possible issue when getting an empty array of a specific type

### ISSUE THREAD

**Issue by JRoy** [SpongePowered/Configurate#411]
When using `ConfigurationNode#getList(String.class)` with the following example yml file on the "mail" node, an exception is raised.

Exception:

```md
[11:47:17] [Server thread/ERROR]: [Essentials] [mail, 0] of type java.lang.String: Value must be provided as a scalar!
com.earth2me.essentials.libs.configurate.serialize.SerializationException: [mail, 0] of type java.lang.String: Value must be provided as a scalar!
	at com.earth2me.essentials.libs.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:101) ~[?:?]
	at com.earth2me.essentials.libs.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:58) ~[?:?]
	at com.earth2me.essentials.libs.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:151) ~[?:?]
	at com.earth2me.essentials.libs.configurate.ConfigurationNode.getList(ConfigurationNode.java:705) ~[?:?]
	at com.earth2me.essentials.config.EssentialsConfiguration.getList(EssentialsConfiguration.java:170) ~[?:?]
	at com.earth2me.essentials.EssentialsUpgrade.convertMailList(EssentialsUpgrade.java:176) ~[?:?]
	at com.earth2me.essentials.EssentialsUpgrade.afterSettings(EssentialsUpgrade.java:1013) ~[?:?]
	at com.earth2me.essentials.Essentials.onEnable(Essentials.java:325) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

Example YML File:
```yml
timestamps:
  login: 1491756022792
  logout: 1491756145765
lastlocation:
  world: world
  x: 555.5
  y: 64.0
  z: 692.5
  yaw: -0.3022766
  pitch: -0.59999186
logoutlocation:
  world: cleanroom
  x: 19.69999998807907
  y: 65.0
  z: -171.2967000893625
  yaw: 306.5454
  pitch: 37.126335
ip-address: 0.0.0.0
last-account-name: mikk377i
mail: []
```

**Comment by jpenilla** [comment]
Getting a similar error loading command settings in Carbon after updating to `4.2.0-SNAPSHOT`, although the array isn't empty:
```
[19:44:35 ERROR]: [CarbonChat] Failed to load config 'plugins/CarbonChat/command-settings.conf'
carbonchat.libs.org.spongepowered.configurate.serialize.SerializationException: [settings, carbon:clearchat, aliases] of type java.lang.String: Value must be provided as a scalar!
	at carbonchat.libs.org.spongepowered.configurate.serialize.ScalarSerializer.deserialize(ScalarSerializer.java:107) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.serialize.AbstractListChildSerializer.deserialize(AbstractListChildSerializer.java:72) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:76) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:56) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:230) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.serialize.TypeSerializer.deserialize(TypeSerializer.java:96) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.serialize.MapSerializer.deserialize(MapSerializer.java:71) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.serialize.MapSerializer.deserialize(MapSerializer.java:35) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load0(ObjectMapperImpl.java:76) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperImpl.load(ObjectMapperImpl.java:56) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.objectmapping.ObjectMapperFactoryImpl.deserialize(ObjectMapperFactoryImpl.java:230) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.AbstractConfigurationNode.get0(AbstractConfigurationNode.java:203) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.AbstractConfigurationNode.get(AbstractConfigurationNode.java:161) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at carbonchat.libs.org.spongepowered.configurate.ConfigurationNode.get(ConfigurationNode.java:521) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at net.draycia.carbon.common.config.ConfigManager.load(ConfigManager.java:163) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at net.draycia.carbon.common.config.ConfigManager.loadCommandSettings(ConfigManager.java:110) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at net.draycia.carbon.common.CarbonChatInternal.init(CarbonChatInternal.java:105) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at net.draycia.carbon.paper.CarbonChatPaper.onEnable(CarbonChatPaper.java:98) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at net.draycia.carbon.paper.CarbonPaperBootstrap.onEnable(CarbonPaperBootstrap.java:44) ~[carbonchat-paper-3.0.0-SNAPSHOT+2a4da56.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-280]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-280]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-280]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-280]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Relevant section of config:
```hocon
settings {
    "carbon:clearchat" {
        aliases=[
            chatclear,
            cc
        ]
        enabled=true
        name=clearchat
    }
}
```

This is part of the default settings, so the second start of the plugin fails with `4.2.0-SNAPSHOT`, worked with `4.1.2`.

Extra context:
```java
@ConfigSerializable
public class CommandConfig {
    private Map<Key, CommandSettings> settings = CloudUtils.defaultCommandSettings();
}
```

```java
@ConfigSerializable
public class CommandSettings {
    private boolean enabled = true;
    private String name = "";
    private String[] aliases = new String[0];
}
```
