### ISSUE TITLE
configurate creating a ton of tmp files that aren't deleted properly

### ISSUE THREAD

**Issue by bloodmc** [SpongePowered/Configurate#73]
http://pastebin.com/WYmWWt6G

Server reported this to me which shows configurate attempting to save to file but gets stuck in a loop since tmp files still exist.

**Comment by lucko** [comment]
Seems like this is still happening frequently

```
[21:49:24 ERROR] [nucleus]: Could not save defaults.
[21:49:24 ERROR] [STDERR]: java.nio.file.AccessDeniedException: C:\Users\luck\Desktop\SV\config\nucleus\102501141641501commands.conf.tmp -> C:\Users\luck\Desktop\SV\config\nucleus\commands.conf
[21:49:24 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[21:49:24 ERROR] [STDERR]:      at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[21:49:24 ERROR] [STDERR]:      at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
[21:49:24 ERROR] [STDERR]:      at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
[21:49:24 ERROR] [STDERR]:      at java.nio.file.Files.move(Unknown Source)
[21:49:24 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AtomicFiles$AtomicFileWriter.close(AtomicFiles.java:94)
[21:49:24 ERROR] [STDERR]:      at java.io.BufferedWriter.close(Unknown Source)
[21:49:24 ERROR] [STDERR]:      at ninja.leaping.configurate.loader.AbstractConfigurationLoader.save(AbstractConfigurationLoader.java:170)
[21:49:24 ERROR] [STDERR]:      at io.github.nucleuspowered.nucleus.config.bases.AbstractStandardNodeConfig.save(AbstractStandardNodeConfig.java:35)
[21:49:24 ERROR] [STDERR]:      at io.github.nucleuspowered.nucleus.internal.qsml.module.StandardModule.loadCommands(StandardModule.java:280)
[21:49:24 ERROR] [STDERR]:      at io.github.nucleuspowered.nucleus.internal.qsml.module.StandardModule.onEnable(StandardModule.java:212)
[21:49:24 ERROR] [STDERR]:      at io.github.nucleuspowered.relocate.uk.co.drnaylor.quickstart.loaders.ModuleEnabler.enableModule(ModuleEnabler.java:51)
[21:49:24 ERROR] [STDERR]:      at io.github.nucleuspowered.relocate.uk.co.drnaylor.quickstart.ModuleContainer$EnablePhase$2.onModuleAction(ModuleContainer.java:925)
[21:49:24 ERROR] [STDERR]:      at io.github.nucleuspowered.relocate.uk.co.drnaylor.quickstart.ModuleContainer.loadModules(ModuleContainer.java:543)
[21:49:24 ERROR] [STDERR]:      at io.github.nucleuspowered.nucleus.NucleusPlugin.onInitLate(NucleusPlugin.java:421)
[21:49:24 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GameInitializationEventListener_NucleusPlugin_onInitLate6.handle(Unknown Source)
[21:49:24 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[21:49:24 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:423)
[21:49:24 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:455)
[21:49:24 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:223)
[21:49:24 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:231)
[21:49:24 ERROR] [STDERR]:      at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:145)
[21:49:24 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$zpo000(SourceFile:1243)
[21:49:24 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:191)
[21:49:24 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:434)
[21:49:24 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)
```

![](https://luck.sh/IykUpXimfp6Favv9SQJpkKMg4VM=)

The javadocs for `StandardCopyOption#ATOMIC_MOVE ATOMIC_MOVE` state:

> The move is performed as an atomic file system operation and all other options are ignored. If the target file exists then it is implementation specific if the existing file is replaced or this method fails by throwing an {@link IOException}.

In the example above, it seems that commands.conf already existed? So perhaps `AccessDeniedException` is thrown when the file already exists? Probably requires more digging, but I thought I'd just dump the extra info here.

I think at the very least we should try to cleanup the temporary file.

Failing that, we could probably opt to make the default writer a standard BufferedWriter, as opposed to `AtomicFiles$AtomicFileWriter`?

**Comment by XakepSDK** [comment]
`I think at the very least we should try to cleanup the temporary file.`
I don't think so, temporary file is newest version made by plugin, if admin don't want to loose newest data, he can use this temp file.

**Comment by dualspiral** [comment]
That nucleus one is my fault, same problem and reason as https://github.com/SpongePowered/SpongeForge/issues/1991#issuecomment-364886453 - I'm saving that commands file way too often during startup - once per module. I should fix that at my end, I don't think there is anything to be done here.

**Comment by lucko** [comment]
In which case yes, definitely a race condition between these calls

https://github.com/SpongePowered/configurate/blob/a22db702da02a7e645746d69f8a8c5bf60b2a862/configurate-core/src/main/java/ninja/leaping/configurate/loader/AtomicFiles.java#L68

https://github.com/SpongePowered/configurate/blob/a22db702da02a7e645746d69f8a8c5bf60b2a862/configurate-core/src/main/java/ninja/leaping/configurate/loader/AtomicFiles.java#L94

Maybe you're right that nothing can be done, but I'd expect that an "atomic" writer wouldn't have this flaw - as a race issue is the exact thing it's trying to combat.

**Comment by lucko** [comment]
If a `AccessDeniedException` or `FileAlreadyExistsException` (windows & mac/linux respectively) is thrown in the `#close` method, we can assume that it is because another process has saved a new file to that location in the time that the current process has been writing to the (since moved) previous file.

I would say the most appropriate course of action in that case is to override the "new" file.

It actually seems like this may have been intended originally, from the presence of both the `StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING` flags.

However, the JavaDocs for the `ATOMIC_MOVE` option state:

> The move is performed as an atomic file system operation and all other options are ignored.

Meaning that `REPLACE_EXISTING` is ignored.

I propose that a catch block for `AccessDeniedException` and `FileAlreadyExistsException` is added around the `#move` call, to re-try using the `REPLACE_EXISTING` if the atomic operation fails. Doing so would (I think) achieve the original intended behaviour of this writer.

**Comment by bloodmc** [comment]
@lucko any chance you can push a fix for this?

**Comment by zml2008** [comment]
Has anyone been able to reproduce this issue recently? I saw one of these go by, and it turned out to be that the original file was locked by some other process. 

Looking into the JDK implementation, on both Windows and Linux atomic moves will replace the existing files -- see [Windows] and [Unix] (Linux and macOS). POSIX systems use the [rename()] libc function, so even though a replace existing flag is not specifically specified, it's included, so I doubt those copy options would be the issue.

[Windows]: https://github.com/openjdk/jdk/blob/jdk8-b116/jdk/src/windows/classes/sun/nio/fs/WindowsFileCopy.java#L293
[Unix]: https://github.com/openjdk/jdk/blob/fc728278c2bc4af041f2ffa1fba54bcdc4c0e4e3/src/java.base/unix/classes/sun/nio/fs/UnixCopyFile.java#L407
[rename()]: http://man7.org/linux/man-pages/man2/rename.2.html

**Comment by zml2008** [comment]
Alright, since I haven't heard any responses to this in a bit, I'm going to continue believing that this just happens from users having the original configuration file open in their editor while Configurate is trying to save. In that case, I think having temporary files with what was supposed to have been saved is the desired outcome to avoid any data loss.

Feel free to bring this up again if there are any temporary file issues that can't be traced down to windows file locking.
